// <auto-generated />
using System;
using Bitirme.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bitirme.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bitirme.Models.AlisverisSepeti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UrunId");

                    b.ToTable("AlisverisSepetleri");
                });

            modelBuilder.Entity("Bitirme.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adres = "Bahçelievler 2. Sokak",
                            Ilce = "Merkez",
                            Isim = "Cevdet Kuyumculuk",
                            PostaKodu = "19000",
                            Sehir = "Çorum",
                            TelefonNo = "05355355353"
                        },
                        new
                        {
                            Id = 2,
                            Adres = "Fatih Mah. 2. Sokak",
                            Ilce = "Kızılay",
                            Isim = "Tuğran Kuyum & Mücevher",
                            PostaKodu = "06000",
                            Sehir = "Ankara",
                            TelefonNo = "05334567353"
                        },
                        new
                        {
                            Id = 3,
                            Adres = "Çarşı Cad. 6. Sokak",
                            Ilce = "Eminönü",
                            Isim = "Altın Kuyumculuk",
                            PostaKodu = "34000",
                            Sehir = "İstanbul",
                            TelefonNo = "05359992378"
                        },
                        new
                        {
                            Id = 4,
                            Adres = "Alaattin Keykubat Cad Yeşil Sokak",
                            Ilce = "Merkez",
                            Isim = "Gümüşoğlu Kuyumculuk",
                            PostaKodu = "41000",
                            Sehir = "Konya",
                            TelefonNo = "05359540099"
                        });
                });

            modelBuilder.Entity("Bitirme.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Siparis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "GramAltin",
                            Siparis = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "KulceAltin",
                            Siparis = 2
                        },
                        new
                        {
                            Id = 3,
                            Ad = "ZiynetAltin",
                            Siparis = 3
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Diger",
                            Siparis = 4
                        });
                });

            modelBuilder.Entity("Bitirme.Models.SiparisBaslik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GonderimZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KargoFirmasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KargoTakipNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiparisDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SiparisToplamTutar")
                        .HasColumnType("float");

                    b.Property<DateTime>("SiparisZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("SiparisBasliks");
                });

            modelBuilder.Entity("Bitirme.Models.SiparisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<int>("SiparisBaslikId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiparisBaslikId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisDetays");
                });

            modelBuilder.Entity("Bitirme.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<double>("Fiyat100")
                        .HasColumnType("float");

                    b.Property<double>("Fiyat50")
                        .HasColumnType("float");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<double>("ListeFiyat")
                        .HasColumnType("float");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunMarka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed feugiat arcu, sed facilisis ex. Aenean imperdiet molestie bibendum. Suspendisse bibendum orci id lacus efficitur, non mollis nisi laoreet. Ut et sollicitudin tellus, vitae eleifend urna. In elementum purus nec urna posuere, ut consequat nisl mattis. Vestibulum laoreet quis leo iaculis ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n\r\nCras ultricies ante ut diam rhoncus vestibulum. Integer a consequat quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec sapien vitae dui tristique facilisis et id mi. Proin venenatis malesuada ligula. Cras feugiat urna eu dolor eleifend feugiat. Nunc mollis erat at ipsum blandit pulvinar. ",
                            Fiyat = 1900.0,
                            Fiyat100 = 1880.0,
                            Fiyat50 = 1890.0,
                            KategoriId = 1,
                            ListeFiyat = 1900.0,
                            ResimUrl = "/resimler/urunler/gramaltin.jpg",
                            UrunAdi = "Gram Altın",
                            UrunKodu = "grm01",
                            UrunMarka = "Ahlatcı Rafineri"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed feugiat arcu, sed facilisis ex. Aenean imperdiet molestie bibendum. Suspendisse bibendum orci id lacus efficitur, non mollis nisi laoreet. Ut et sollicitudin tellus, vitae eleifend urna. In elementum purus nec urna posuere, ut consequat nisl mattis. Vestibulum laoreet quis leo iaculis ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n\r\nCras ultricies ante ut diam rhoncus vestibulum. Integer a consequat quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec sapien vitae dui tristique facilisis et id mi. Proin venenatis malesuada ligula. Cras feugiat urna eu dolor eleifend feugiat. Nunc mollis erat at ipsum blandit pulvinar.  ",
                            Fiyat = 3500.0,
                            Fiyat100 = 3470.0,
                            Fiyat50 = 3480.0,
                            KategoriId = 1,
                            ListeFiyat = 3500.0,
                            ResimUrl = "/resimler/urunler/ceyrekaltin.jpg",
                            UrunAdi = "Çeyrek Altın",
                            UrunKodu = "cyr01",
                            UrunMarka = "Ahlatcı Rafineri"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Rafineri onaylı ve belgeli, özel kutusunda gram altın  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed feugiat arcu, sed facilisis ex. Aenean imperdiet molestie bibendum. Suspendisse bibendum orci id lacus efficitur, non mollis nisi laoreet. Ut et sollicitudin tellus, vitae eleifend urna. In elementum purus nec urna posuere, ut consequat nisl mattis. Vestibulum laoreet quis leo iaculis ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n\r\nCras ultricies ante ut diam rhoncus vestibulum. Integer a consequat quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec sapien vitae dui tristique facilisis et id mi. Proin venenatis malesuada ligula. Cras feugiat urna eu dolor eleifend feugiat. Nunc mollis erat at ipsum blandit pulvinar. ",
                            Fiyat = 5000.0,
                            Fiyat100 = 4750.0,
                            Fiyat50 = 4990.0,
                            KategoriId = 1,
                            ListeFiyat = 5000.0,
                            ResimUrl = "/resimler/urunler/yarim.jpg",
                            UrunAdi = "Yarım Altın",
                            UrunKodu = "yrm01",
                            UrunMarka = "Ahlatcı Rafineri"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Rafineri onaylı ve belgeli, özel kutusunda 10 Gram Külçe Altın  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed feugiat arcu, sed facilisis ex. Aenean imperdiet molestie bibendum. Suspendisse bibendum orci id lacus efficitur, non mollis nisi laoreet. Ut et sollicitudin tellus, vitae eleifend urna. In elementum purus nec urna posuere, ut consequat nisl mattis. Vestibulum laoreet quis leo iaculis ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n\r\nCras ultricies ante ut diam rhoncus vestibulum. Integer a consequat quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec sapien vitae dui tristique facilisis et id mi. Proin venenatis malesuada ligula. Cras feugiat urna eu dolor eleifend feugiat. Nunc mollis erat at ipsum blandit pulvinar.  ",
                            Fiyat = 18000.0,
                            Fiyat100 = 17500.0,
                            Fiyat50 = 17800.0,
                            KategoriId = 2,
                            ListeFiyat = 18000.0,
                            ResimUrl = "/resimler/urunler/20gramkulce.png",
                            UrunAdi = "20 Gram Külçe Altın",
                            UrunKodu = "Kulce0001",
                            UrunMarka = "Ahlatcı Rafineri"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Rafineri onaylı ve belgeli, özel kutusunda 30 gram 18 Ayar şık kadın bilekliği  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed feugiat arcu, sed facilisis ex. Aenean imperdiet molestie bibendum. Suspendisse bibendum orci id lacus efficitur, non mollis nisi laoreet. Ut et sollicitudin tellus, vitae eleifend urna. In elementum purus nec urna posuere, ut consequat nisl mattis. Vestibulum laoreet quis leo iaculis ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n\r\nCras ultricies ante ut diam rhoncus vestibulum. Integer a consequat quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec sapien vitae dui tristique facilisis et id mi. Proin venenatis malesuada ligula. Cras feugiat urna eu dolor eleifend feugiat. Nunc mollis erat at ipsum blandit pulvinar. ",
                            Fiyat = 50000.0,
                            Fiyat100 = 49700.0,
                            Fiyat50 = 49800.0,
                            KategoriId = 3,
                            ListeFiyat = 50000.0,
                            ResimUrl = "/resimler/urunler/30gramhasirseritbilezik.jpg",
                            UrunAdi = "30 Gram Altın Bileklik",
                            UrunKodu = "Ziynet001",
                            UrunMarka = "Ahlatcı Rafineri"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Rafineri onaylı ve belgeli, özel hediye kutusunda 50 gram 22 Ayar Burma Bilezik  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed feugiat arcu, sed facilisis ex. Aenean imperdiet molestie bibendum. Suspendisse bibendum orci id lacus efficitur, non mollis nisi laoreet. Ut et sollicitudin tellus, vitae eleifend urna. In elementum purus nec urna posuere, ut consequat nisl mattis. Vestibulum laoreet quis leo iaculis ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\r\n\r\nCras ultricies ante ut diam rhoncus vestibulum. Integer a consequat quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec sapien vitae dui tristique facilisis et id mi. Proin venenatis malesuada ligula. Cras feugiat urna eu dolor eleifend feugiat. Nunc mollis erat at ipsum blandit pulvinar. ",
                            Fiyat = 85000.0,
                            Fiyat100 = 84600.0,
                            Fiyat50 = 84850.0,
                            KategoriId = 3,
                            ListeFiyat = 85000.0,
                            ResimUrl = "/resimler/urunler/30grhasirseritbilezik.jpg",
                            UrunAdi = "50 Gram Burma Bilezik",
                            UrunKodu = "Ziynet002",
                            UrunMarka = "Ahlatcı Rafineri"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bitirme.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Bitirme.Models.AlisverisSepeti", b =>
                {
                    b.HasOne("Bitirme.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitirme.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Bitirme.Models.SiparisBaslik", b =>
                {
                    b.HasOne("Bitirme.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Bitirme.Models.SiparisDetay", b =>
                {
                    b.HasOne("Bitirme.Models.SiparisBaslik", "SiparisBaslik")
                        .WithMany()
                        .HasForeignKey("SiparisBaslikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bitirme.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiparisBaslik");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Bitirme.Models.Urun", b =>
                {
                    b.HasOne("Bitirme.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bitirme.Models.ApplicationUser", b =>
                {
                    b.HasOne("Bitirme.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
